In [1]:
from bp.section1_video5_data import get_data 

In [3]:
from sklearn import model_selection

In [4]:
from xgboost import XGBClassifier

In [5]:
import numpy as np

In [6]:
seed=123

In [7]:
X, Y = get_data('data/video1_diabetes.csv')

In [8]:
X, Y

(array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 2.66e+01, 3.51e-01, 3.10e+01],
        [1.00e+00, 8.90e+01, 6.60e+01, ..., 2.81e+01, 1.67e-01, 2.10e+01],
        [5.00e+00, 1.16e+02, 7.40e+01, ..., 2.56e+01, 2.01e-01, 3.00e+01],
        ...,
        [6.00e+00, 1.90e+02, 9.20e+01, ..., 3.55e+01, 2.78e-01, 6.60e+01],
        [9.00e+00, 1.70e+02, 7.40e+01, ..., 4.40e+01, 4.03e-01, 4.30e+01],
        [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.01e+01, 3.49e-01, 4.70e+01]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 

In [9]:
c = XGBClassifier(random_seed=seed)

In [10]:
results= c.fit(X, Y)

In [11]:
results_kfold_model = model_selection.cross_val_score(c, X, Y, cv=10)

In [12]:
results_kfold_model.mean()*100

71.66666666666666

In [13]:
new_data=np.array([[0, 148, 72, 0, 0, 33, 0, 50]])

In [14]:
p=c.predict(new_data)

In [15]:
p

array([1])

In [17]:
pred=c.predict_proba(new_data)

In [18]:
pred


array([[0.32171988, 0.6782801 ]], dtype=float32)